services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: whalefox-gluetun
    cap_add:
      - NET_ADMIN
    env_file: whalefox.env
    ports:
      - 8888:8888/tcp # For Gluetun's built-in HTTP proxy (if needed)
      - 8388:8388/tcp # For Gluetun's built-in Shadowsocks server
      - 8388:8388/udp # For Gluetun's built-in Shadowsocks server
      - ${FF_PORT}:3000 # Firefox
      #- 3001:3001 # Firefox VNC
    volumes:
      - gluetun:/gluetun
    restart: unless-stopped

  browser:
    image: lscr.io/linuxserver/firefox:latest
    container_name: whalefox
    env_file: whalefox.env
    network_mode: "service:gluetun"
    shm_size: ${SHM_SIZE:-2g} # Increase shared memory size for Firefox
    volumes:
      - whalefox:/config:rw
      - ./downloads:/downloads:rw
    restart: unless-stopped

volumes:
  gluetun:
    driver: local
  whalefox:
    driver: local